version: '3.9'

services:
  test-server:
    container_name: test-server
    build:
      context: ./
      dockerfile: ./server/Dockerfile

  test-client:
    container_name: test-client
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    depends_on:
      - test-server

  test-haproxy:
    container_name: test-haproxy
    build:
      context: ./
      dockerfile: ./haproxy/Dockerfile
    depends_on:
      - test-server
